### ISSUE TITLE
Unexpected token export 

### ISSUE THREAD

**Issue by Geczy** [5to6/5to6-codemod#52]
```jscodeshift -t node_modules/5to6-codemod/transforms/amd.js src```

Result:

```C:\Users\Matt\Documents\GitHub\m2m-launch-ui\node_modules\lodash\lodash.js:17095
    export default _;
    ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Matt\AppData\Local\Yarn\config\global\node_modules\babel-regist
er\lib\node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
All done.
Results:
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.729seconds
```

**Comment by xjamundx** [comment]
I guess we don't have support for ES modules. Should be fairly easy to add, but I unfortunately don't have the time to add it. Will require an updated parser.
