### ISSUE TITLE
Error when running exports transformation with shadowed variable

### ISSUE THREAD

**Issue by daveisfera** [5to6/5to6-codemod#55]
This the stacktrace:
```
 ERR test.js Transformation error (Identifier 'ids' has already been declared (3:12))
SyntaxError: Identifier 'ids' has already been declared (3:12)
    at Object.raise (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:6322:17)
    at ScopeHandler.checkRedeclarationInScope (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:3754:12)
    at ScopeHandler.declareName (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:3720:12)
    at Object.checkLVal (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8006:22)
    at Object.checkLVal (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:373:15)
    at Object.parseVarId (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10441:10)
    at Object.parseVar (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10412:12)
    at Object.parseVarStatement (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10234:10)
    at Object.parseStatementContent (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9830:21)
    at Object.parseStatement (/Users/dlj/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9763:17)
```

And here's a simple file that demonstrates the issue:
```
class Repeated {
    doSomething(ids) { 
        let ids = { ids: ids.toString() };
        return ids;
    }
}
```

**Comment by xjamundx** [comment]
Thanks for the report. Which transform are you using?

**Comment by xjamundx** [comment]
FYI this is legitimately a syntax error:

```js
function a(b) { let b; }
```

so probably we'll need to detect these cases somehow... 🤔

**Comment by xjamundx** [comment]
Oh was this `var` to `let`?

**Comment by dave-nm** [comment]
It was the exports transformation.
